name: CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-test:
    name: Deploy to testing environment
    runs-on: ubuntu-latest
    environment:
      name: testing
      url: https://taxonomy-test.uitdatabank.be

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --content-type application/xml
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-1'
          SOURCE_DIR: 'xml'

      - name: Invalidate CloudFront distribution
        uses: chetan/invalidate-cloudfront-action@v1.3
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-prod:
    name: Deploy to production environment
    needs: [deploy-test]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://taxonomy.uitdatabank.be

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --content-type application/xml
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-1'
          SOURCE_DIR: 'xml'

      - name: Invalidate CloudFront distribution
        uses: chetan/invalidate-cloudfront-action@v1.3
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: 'build'
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON_EMOJI: ':octocat:'
          SLACK_USERNAME: 'Github Actions'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
